FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o /migrate ./cmd/migrate

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /migrate /migrate
COPY --from=builder /app/migrations /migrations

WORKDIR /

ENTRYPOINT ["/migrate"]
CMD ["up"]